"""add is_top

Revision ID: 6ca7a25faeef
Revises: 25c9ee543a87
Create Date: 2020-06-10 16:04:42.216389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca7a25faeef'
down_revision = '25c9ee543a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_top', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_top')
    # ### end Alembic commands ###
