"""add post source

Revision ID: 87a5bfdd6176
Revises: 0aaecf7e67c9
Create Date: 2020-06-03 15:31:08.670685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a5bfdd6176'
down_revision = '0aaecf7e67c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('source', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'source')
    # ### end Alembic commands ###
