"""post add like

Revision ID: 881a88aa10c3
Revises: 21814f4be986
Create Date: 2020-05-27 17:17:17.867429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881a88aa10c3'
down_revision = '21814f4be986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like')
    # ### end Alembic commands ###
