"""fix likes

Revision ID: c9d102a57c54
Revises: 881a88aa10c3
Create Date: 2020-05-27 17:19:11.402458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9d102a57c54'
down_revision = '881a88aa10c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.Integer(), nullable=True))
    op.drop_column('post', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###
